version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec passenger start -p 3000 -b '0.0.0.0'
    volumes:
      - .:/olympic_flame_api
    ports:
      - "3000:3000"
    depends_on:
      - db